export const ERP_DOMAIN_EVENTS = [
  'customer.created',
  'customer.updated',
  'customer.state_changed',
  'customer.archived',
  'part.sku.created',
  'part.sku.updated',
  'part.sku.state_changed',
  'inventory.location.created',
  'inventory.location.state_changed',
  'inventory.bin.created',
  'inventory.bin.state_changed',
  'inventory.lot.received',
  'inventory.lot.reserved',
  'inventory.lot.released',
  'inventory.lot.consumed',
  'inventory.shortage_detected',
  'inventory.part_substitution_configured',
  'inventory.part_substitution_used',
  'inventory.reservation_allocated',
  'inventory.uom_conversion_applied',
  'inventory.adjustment_recorded',
  'inventory.transfer_completed',
  'inventory.cycle_count_started',
  'inventory.cycle_count_completed',
  'inventory.work_order_consumption_recorded',
  'inventory.purchase_order_linked',
  'inventory.ledger_entry_recorded',
  'inventory.ledger_queried',
  'vendor.created',
  'vendor.updated',
  'vendor.state_changed',
  'purchase_order.created',
  'purchase_order.approved',
  'purchase_order.sent',
  'purchase_order.partially_received',
  'purchase_order.received',
  'purchase_order.cancelled',
  'cart.vehicle.registered',
  'cart.vehicle.state_changed',
  'cart.vehicle.completed',
  'build.configuration.saved',
  'build.configuration.locked',
  'build.configuration.released',
  'bom.created',
  'bom.approved',
  'bom.obsolete',
  'routing.step.created',
  'routing.step.updated',
  'routing.step.deprecated',
  'work_order.created',
  'work_order.released',
  'work_order.started',
  'work_order.blocked',
  'work_order.completed',
  'work_order.cancelled',
  'technician_task.created',
  'technician_task.assigned',
  'technician_task.started',
  'technician_task.blocked',
  'technician_task.completed',
  'ticket.rework.created',
  'ticket.rework.state_changed',
  'ticket.rework.closed',
  'build_slot.planned',
  'build_slot.locked',
  'build_slot.capacity_exceeded',
  'build_slot.closed',
  'labor_capacity.updated',
  'labor_capacity.exceeded',
  'labor_capacity.closed',
  'invoice_sync.started',
  'invoice_sync.succeeded',
  'invoice_sync.failed',
  'invoice_sync.retried',
  'invoice_sync.cancelled',
  'customer_sync.started',
  'customer_sync.succeeded',
  'customer_sync.failed',
  'customer_sync.skipped',
  'payment_sync.started',
  'payment_sync.completed',
  'payment_sync.failed',
  'qb.webhook.received',
  'qb.connection.established',
  'qb.connection.lost',
  'file_attachment.uploaded',
  'file_attachment.available',
  'file_attachment.quarantined',
  'reconciliation.completed',
  'reconciliation.failed',
  'reconciliation.record_resolved',
  'audit.event.recorded',
  'outbox.event.persisted'
] as const;

export type DomainEventName = (typeof ERP_DOMAIN_EVENTS)[number];

export interface DomainEvent<TPayload> {
  name: DomainEventName;
  version: number;
  payload: TPayload;
  correlationId: string;
  occurredAt: string;
}
